mqtt_client:
  ros__parameters:
    # MQTT connection
    broker_address: 192.168.1.115
    broker_port: 1883
    username: ""
    password: ""
    # Bridge definitions: list of ros2mqtt and mqtt2ros
    ros2mqtt:
      - ros_topic: '/cmd_vel'
        mqtt_topic: 'robot/control'
        # message type must match the ROS msg
        msg_type: 'geometry_msgs/msg/Twist'
        # choose serialization: 'json' or 'msgpack'
        serialization: 'json'
    # (If you also want to receive commands back from MQTT:)
    mqtt2ros:
      - mqtt_topic: 'robot/control_back'
        ros_topic: '/cmd_vel_back'
        msg_type: 'geometry_msgs/msg/Twist'
        serialization: 'json'
