map_id: df_map
configured: true
waypoints:
  home:
    x: 0.0341
    y: 0.0243
    theta: -0.0027
    allowed_deviation_xy: 0.2
    allowed_deviation_theta: 0.3
  short_test:
    x: 0.9404
    y: -2.0552
    theta: -2.1335
    allowed_deviation_xy: 0.2
    allowed_deviation_theta: 0.3
  crane_handover:
    x: 2.7544
    y: -2.0849
    theta: 2.59
    allowed_deviation_xy: 0.15
    allowed_deviation_theta: 0.15
  warehouse_dropoff:
    x: 3.1739
    y: 0.1588
    theta: 0.9971
    allowed_deviation_xy: 0.2
    allowed_deviation_theta: 0.3
