map_id: df_map
configured: true
waypoints:
  home:
    x: 0.1729
    y: 0.015
    theta: -0.0073
    allowed_deviation_xy: 0.18
    allowed_deviation_theta: 0.2
  short_test:
    x: 1.5196
    y: -2.2472
    theta: -1.5865
    allowed_deviation_xy: 0.18
    allowed_deviation_theta: 0.2
  crane_handover:
    x: 3.0607
    y: -1.3256
    theta: 3.1241
    allowed_deviation_xy: 0.12
    allowed_deviation_theta: 0.15
  warehouse_dropoff:
    x: 2.2782
    y: 0.8154
    theta: 1.554
    allowed_deviation_xy: 0.18
    allowed_deviation_theta: 0.2
