#!/usr/bin/env bash
# One-time, idempotent shell setup for a ROX robot or remote operator computer.
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROLE="${1:-}"
[[ -n "$ROLE" ]] && shift || true

ROBOT_IP="${ROX_ROBOT_IP:-192.168.50.50}"
ROBOT_USER="${ROX_ROBOT_USER:-neobotix}"
REMOTE_PROJECT="${ROX_REMOTE_PROJECT:-/home/neobotix/Projects/VDA5050-Paper-Dev}"
NEO_WS="${NEOBOTIX_WS:-}"

usage() {
  cat <<EOF2
Usage:
  ./scripts/install_rox_shell.sh operator [OPTIONS]
  ./scripts/install_rox_shell.sh robot [OPTIONS]

Options:
  --neobotix-ws PATH   Installed Neobotix/ROX workspace
  --robot-ip IP        ROX-Diff address (default: 192.168.50.50)
  --robot-user USER    SSH user on ROX-Diff (default: neobotix)
  --remote-project PATH
                       Repository path on ROX-Diff

Examples:
  ./scripts/install_rox_shell.sh operator --neobotix-ws "$HOME/neobotix_view_ws"
  ./scripts/install_rox_shell.sh robot --neobotix-ws "$HOME/ros2_workspace"
EOF2
}

case "$ROLE" in
  operator|robot) ;;
  help|-h|--help|"") usage; exit 0 ;;
  *) echo "ERROR: role must be 'operator' or 'robot'" >&2; usage; exit 2 ;;
esac

while [[ $# -gt 0 ]]; do
  case "$1" in
    --neobotix-ws)
      [[ $# -ge 2 ]] || { echo "ERROR: --neobotix-ws needs a path" >&2; exit 2; }
      NEO_WS="$2"; shift 2 ;;
    --robot-ip)
      [[ $# -ge 2 ]] || { echo "ERROR: --robot-ip needs an address" >&2; exit 2; }
      ROBOT_IP="$2"; shift 2 ;;
    --robot-user)
      [[ $# -ge 2 ]] || { echo "ERROR: --robot-user needs a user" >&2; exit 2; }
      ROBOT_USER="$2"; shift 2 ;;
    --remote-project)
      [[ $# -ge 2 ]] || { echo "ERROR: --remote-project needs a path" >&2; exit 2; }
      REMOTE_PROJECT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown option '$1'" >&2; usage; exit 2 ;;
  esac
done

if [[ -z "$NEO_WS" ]]; then
  if [[ "$ROLE" == "robot" ]]; then
    candidates=("$HOME/ros2_workspace" "$HOME/rox_ws" "$HOME/neobotix_view_ws")
  else
    candidates=("$HOME/neobotix_view_ws" "$HOME/rox_ws" "$HOME/neobotix_ws" "$HOME/ros2_workspace")
  fi
  for candidate in "${candidates[@]}"; do
    if [[ -f "$candidate/install/setup.bash" ]]; then
      NEO_WS="$candidate"
      break
    fi
  done
fi

[[ -n "$NEO_WS" ]] || {
  echo "ERROR: could not auto-detect the Neobotix workspace." >&2
  echo "Pass --neobotix-ws /absolute/path/to/workspace" >&2
  exit 2
}
[[ -f "$NEO_WS/install/setup.bash" ]] || {
  echo "ERROR: setup not found: $NEO_WS/install/setup.bash" >&2
  exit 2
}
[[ -f "/opt/ros/jazzy/setup.bash" ]] || {
  echo "ERROR: ROS 2 Jazzy is not installed at /opt/ros/jazzy" >&2
  exit 2
}

CONFIG_DIR="$HOME/.config/rox"
CONFIG_FILE="$CONFIG_DIR/rox.env"
mkdir -p "$CONFIG_DIR"

{
  echo "# Generated by $ROOT/scripts/install_rox_shell.sh"
  printf 'export ROX_ROLE=%q\n' "$ROLE"
  printf 'export VDA5050_PROJECT=%q\n' "$ROOT"
  printf 'export NEOBOTIX_WS=%q\n' "$NEO_WS"
  printf 'export ROS_DISTRO=%q\n' "jazzy"
  printf 'export RMW_IMPLEMENTATION=%q\n' "rmw_cyclonedds_cpp"
  printf 'export ROS_DOMAIN_ID=%q\n' "169"
  printf 'export ROS_AUTOMATIC_DISCOVERY_RANGE=%q\n' "SUBNET"
  printf 'export ROX_ROBOT_IP=%q\n' "$ROBOT_IP"
  printf 'export ROX_ROBOT_USER=%q\n' "$ROBOT_USER"
  printf 'export ROX_REMOTE_PROJECT=%q\n' "$REMOTE_PROJECT"
  if [[ "$ROLE" == "operator" ]]; then
    printf 'export ROS_STATIC_PEERS=%q\n' "$ROBOT_IP"
  fi
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

python3 - "$HOME/.bashrc" "$ROOT/scripts/rox_env.sh" <<'PY'
from pathlib import Path
import sys

bashrc = Path(sys.argv[1])
env_script = sys.argv[2]
start = "# >>> VDA5050 ROX environment >>>"
end = "# <<< VDA5050 ROX environment <<<"
text = bashrc.read_text(encoding="utf-8") if bashrc.exists() else ""
lines = text.splitlines()
out = []
skipping = False
for line in lines:
    if line.strip() == start:
        skipping = True
        continue
    if skipping and line.strip() == end:
        skipping = False
        continue
    if not skipping:
        out.append(line)
while out and not out[-1].strip():
    out.pop()
out.extend([
    "",
    start,
    f'if [ -f "{env_script}" ]; then',
    f'  source "{env_script}"',
    "fi",
    end,
    "",
])
bashrc.write_text("\n".join(out), encoding="utf-8")
PY

# Reset the ROS daemon once under the newly installed environment. This avoids
# retaining a daemon that was started before ROS_STATIC_PEERS was configured.
# shellcheck disable=SC1091
source "$ROOT/scripts/rox_env.sh"
if command -v ros2 >/dev/null 2>&1; then
  ros2 daemon stop >/dev/null 2>&1 || true
  ros2 daemon start >/dev/null 2>&1 || true
fi

echo "ROX shell environment installed."
echo "  role:              $ROLE"
echo "  project:           $ROOT"
echo "  Neobotix workspace: $NEO_WS"
echo "  config:            $CONFIG_FILE"
echo "  bashrc:            $HOME/.bashrc"
if [[ "$ROLE" == "operator" ]]; then
  echo "  robot SSH target:  $ROBOT_USER@$ROBOT_IP"
  echo
  echo "For password-free operation, run once:"
  echo "  ssh-copy-id $ROBOT_USER@$ROBOT_IP"
fi
echo
echo "Open a new terminal or run:"
echo "  exec bash"
echo
echo "Then verify with:"
echo "  rox doctor"
